export const diseases = [
	{ id: 1, name: 'Cildiye' },
	{ id: 2, name: 'Psikiyatri' },
	{ id: 3, name: 'Beslenme ve diyet' },
	{ id: 4, name: 'Psikoloji' },
	{ id: 5, name: 'Çocuk sağlığı ve hastalıkları' },
	{ id: 6, name: 'İç hastalıkları' },
	{ id: 7, name: 'Kadın hastalıkları ve doğum' },
	{ id: 8, name: 'Nöroloji' },
	{ id: 9, name: 'Ortopedi ve travmatoloji' },
	{ id: 10, name: 'Kulak burun boğaz hastalıkları' },
	{ id: 11, name: 'Üroloji' },
	{ id: 12, name: 'Genel cerrahi' },
	{ id: 13, name: 'Beyin ve sinir cerrahisi' },
	{ id: 14, name: 'Fiziksel tıp ve rehabilitasyon' },
	{ id: 15, name: 'Göğüs hastalıkları' },
	// { id: 16, name: 'Kök hüceyrə mütəxəssisi' },
	// { id: 17, name: 'Kosmetoloq' },
	// { id: 18, name: 'Laborant' },
	// { id: 19, name: 'Lazeroloq' },
	// { id: 20, name: 'Loqoped' },
	// { id: 21, name: 'Mama ginekoloq' },
	// { id: 22, name: 'Manual terapevt' },
	// { id: 23, name: 'Nefroloq' },
	// { id: 24, name: 'Neonatoloq' }
];
