export const diseases = [
	{ id: 1, name: 'Allerqoloq' },
	{ id: 2, name: 'Anestezioloq-reanimatoloq' },
	{ id: 3, name: 'Bariatrik cərrah' },
	{ id: 4, name: 'Cərrah-proktoloq' },
	{ id: 5, name: 'Defektoloq' },
	{ id: 6, name: 'Dermatoveneroloq' },
	{ id: 7, name: 'Diyetoloq' },
	{ id: 8, name: 'Endokrinoloq' },
	{ id: 9, name: 'Exo-KQ' },
	{ id: 10, name: 'Fizioterapevt' },
	{ id: 11, name: 'Genetik' },
	{ id: 12, name: 'Hepatoloq' },
	{ id: 13, name: 'İnfeksionist' },
	{ id: 14, name: 'İnvaziv radioloq' },
	{ id: 15, name: 'Kardioloq' },
	{ id: 16, name: 'Kök hüceyrə mütəxəssisi' },
	{ id: 17, name: 'Kosmetoloq' },
	{ id: 18, name: 'Laborant' },
	{ id: 19, name: 'Lazeroloq' },
	{ id: 20, name: 'Loqoped' },
	{ id: 21, name: 'Mama ginekoloq' },
	{ id: 22, name: 'Manual terapevt' },
	{ id: 23, name: 'Nefroloq' },
	{ id: 24, name: 'Neonatoloq' }
];
