export const diseases = [
	{ id: 1, name: 'Cildiye', slug: 'cildiye' },
	{ id: 2, name: 'Psikiyatri', slug: 'psikiyatri' },
	{ id: 3, name: 'Beslenme ve diyet', slug: 'beslenme-ve-diyet' },
	{ id: 4, name: 'Psikoloji', slug: 'psikoloji' },
	{ id: 5, name: 'Çocuk sağlığı ve hastalıkları', slug: 'cocuk-sagligi-ve-hastaliklari' },
	{ id: 6, name: 'İç hastalıkları', slug: 'ic-hastaliklari' },
	{ id: 7, name: 'Kadın hastalıkları ve doğum', slug: 'kadin-hastaliklari-ve-dogum' },
	{ id: 8, name: 'Nöroloji', slug: 'noroloji' },
	{ id: 9, name: 'Ortopedi ve travmatoloji', slug: 'ortopedi-ve-travmatoloji' },
	{ id: 10, name: 'Kulak burun boğaz hastalıkları', slug: 'kulak-burun-bogaz' },
	{ id: 11, name: 'Üroloji', slug: 'uroloji' },
	{ id: 12, name: 'Genel cerrahi', slug: 'genel-cerrahi' },
	{ id: 13, name: 'Beyin ve sinir cerrahisi', slug: 'beyin-ve-sinir-cerrahisi' },
	{ id: 14, name: 'Fiziksel tıp ve rehabilitasyon', slug: 'fiziksel-tip-ve-rehabilitasyon' },
	{ id: 15, name: 'Göğüs hastalıkları', slug: 'gogus-hastaliklari' }
	// { id: 16, name: 'Kök hüceyrə mütəxəssisi' },
	// { id: 17, name: 'Kosmetoloq' },
	// { id: 18, name: 'Laborant' },
	// { id: 19, name: 'Lazeroloq' },
	// { id: 20, name: 'Loqoped' },
	// { id: 21, name: 'Mama ginekoloq' },
	// { id: 22, name: 'Manual terapevt' },
	// { id: 23, name: 'Nefroloq' },
	// { id: 24, name: 'Neonatoloq' }
];
